---
name: Build QMK firmware
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        file:
          - iris-rev5
          - iris-rev7
    steps:
      - name: Disable git safe directory checks
        run: git config --global --add safe.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          submodules: recursive

      - name: Checkout userspace
        uses: actions/checkout@v3
        with:
          path: users/${{ github.actor }}

      - name: Build firmware
        run: qmk compile "users/${{ github.actor }}/${{ matrix.file }}.json"

      - name: Create a timestamp for the build
        shell: bash
        run: echo "TIMESTAMP=$(date +'%Y-%m-%dT%H%M%S')" >> $GITHUB_ENV

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ${{ matrix.file}}__${{ env.TIMESTAMP }}
          path: |
            *.hex
            *.bin
            *.uf2
